### ISSUE TITLE
Pasikartojantys žodžiai/Repeating words

### ISSUE THREAD

**Issue by Friebay** [cr4shboy/lithwords#1]
Prireikė šio sąrašo ir radau šiek tiek pasikartojančių žodžių, pvz.: ['aleksejus', 'elzbieta', 'ilze', 'ramune', 'rustis', 'vaismantas', 'vaismante', 'alantas', 'albinas', 'albrechtas']

Number of words in lithwords.txt: 200444        
Number of words in lithwords_cleaned.txt: 199208

Pridedu failą jeigu kažkam reikės:
[1_cleaned.txt](https://github.com/cr4shboy/lithwords/files/12060862/1_cleaned.txt)

**Comment by cr4shboy** [comment]
Labas,

Ačiū už pastebėjimą. Deduplikavau sąrašą. Pas mane 198034 gavosi.
Jei pastebėsi klaidų - brūkštelk.
